services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-poc
    ports:
      - "9090:9090"
    volumes:
      - "~/Developer/docker-volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
  grafana:
    image: grafana/grafana
    container_name: grafana-poc
    ports:
      - "3000:3000"